#!/usr/bin/env python3


#f: The name of the file to write to.
#n: The name to write into the file.

def write_name_to_file(f, n):
    with open(f, 'w') as file:
        file.write(n)
    print(f"Name '{n}' has been written to '{f}'.")

if __name__ == "__main__":
    f = "my_name.txt"
    n = input("Please enter your name: ")    
    write_name_to_file(f, n)

def helloWorld():
    print('Hello World')

helloWorld()
